import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Logo } from './components/Logo';
import Link from 'next/link';

const NotoSans = localFont({
  src: './fonts/NotoSans.ttf',
  variable: '--font-noto-sans',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${NotoSans.variable} antialiased flex flex-col items-center justify-center bg-card text-black font-[family-name:var(--font-noto-sans)]`}
      >
        <main className="bg-card w-full">{children}</main>
      </body>
    </html>
  );
}
